### PR TITLE
fix: address comparison

### PR DESCRIPTION
**Pull request by jarkkojs**

### CODE REVIEW

**Comment by jarkkojs** [comment]
@npmccallum I need this for my mm code in the shim-sgx. Otherwise I have to diverge, and implement similar ad-hoc construct. I added enough tests to prove that the code is working.

**Comment by npmccallum** [comment]
@jarkkojs I think this PR is invalid. I copied your tests locally without any changes and they all pass.

**Comment by npmccallum** [comment]
@jarkkojs See https://github.com/enarx/primordial/pull/16 . Notice that this PR just contains tests and does not contain the "fixes." All the tests pass.

**Comment by npmccallum** [comment]
@jarkkojs Okay. I figured out the problem you're seeing. It is just that your tests don't actually test it. The problem is that deriving traits like `Eq` causes the compiler to generate a bound on the `U` type even though it is not use (because of `PhantomData`). So here's what I want to see:

1. A test which actually fails.
2. You need to fix the `Offsets` type too.

**Comment by npmccallum** [comment]
@jarkkojs I [merged this](https://github.com/enarx/primordial/commit/805f59e344f0f2ed0e1534cc3a588ef3988f5b8c) instead. Closing.

**Pull request closed without merging**
